### ISSUE TITLE
Fix LDAP Injection

### ISSUE THREAD

**Issue by jorgectf** [abcdabcd987/lxc-gpu#3]
There's an LDAP Injection in `iam/iam.py`:

The source:

```py
@app.route('/manage/ssh-key/<username>')
237 | def get_manage_ssh_key(username):
238 |     if ldap_username_check(username):
239 |         ensure_user(username)
```
Both `ldap_username_check` and `ensure_user` gets to:
```py
res = l.search_s(base, ldap.SCOPE_SUBTREE, 'sAMAccountName=' + username, ['displayName'])
```
or 
```py
u = l.search_s(base, ldap.SCOPE_SUBTREE, 'sAMAccountName=' + username, ['sAMAccountName'])
```

without being sanitized, so special characters won't be escaped.

**Comment by abcdabcd987** [comment]
Thanks for raising the security concern. Unfortunately, this project is no longer maintained. If you could create a pull request to fix the issue, I'd be happy to merge it!

**Comment by jorgectf** [comment]
> Thanks for raising the security concern. Unfortunately, this project is no longer maintained. If you could create a pull request to fix the issue, I'd be happy to merge it!

Great!
